name = "cozy-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "599cb66ab5c235bb62eb59dc77ed2f42"

# Container configuration
[[containers]]
max_instances = 10
name = "cozy-containers"
class_name = "CozySandboxContainer"
image = "../../sandbox-image/Dockerfile"

# Durable Object binding for container
[[durable_objects.bindings]]
name = "MY_CONTAINER"
class_name = "CozySandboxContainer"

# Migration for Durable Object
[[migrations]]
tag = "v1"
new_sqlite_classes = ["CozySandboxContainer"]

# Environment variables
[vars]
ENVIRONMENT = "production"