name = "cozy-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "599cb66ab5c235bb62eb59dc77ed2f42"

# Custom domain
route = "api.cozy.cloud/*"

# Container configuration
[[containers]]
max_instances = 10
name = "cozy-sandbox"
class_name = "CozySandboxContainer"
image = "../../sandbox-image/Dockerfile"

# Durable Object binding for container
[[durable_objects.bindings]]
name = "CONTAINER"
class_name = "CozySandboxContainer"

# Migration for Durable Object
[[migrations]]
tag = "v1"
new_sqlite_classes = ["CozySandboxContainer"]

# Environment variables
[vars]
ENVIRONMENT = "development"

# KV namespace bindings (example)
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-namespace-id"

# Durable Object bindings (example)
# [[durable_objects.bindings]]
# name = "DO"
# class_name = "DurableObject"

# R2 bucket bindings (example)
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "your-bucket-name"