name = "cozy-frontend"
main = "./worker.ts"
compatibility_date = "2025-01-01"
account_id = "599cb66ab5c235bb62eb59dc77ed2f42"

# Workers.dev subdomain deployment
# Custom domain route will be added through dashboard

[site]
bucket = "./dist"

[build]
command = "bun run build"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_URL = "https://cozy-worker.jeremycai.workers.dev"