name = "cozy-web"
main = "./worker.ts"
compatibility_date = "2025-01-01"
account_id = "3f83a47ede5b22c5ab36258d49013e06"

[site]
bucket = "./dist"

[build]
command = "bun run build"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_URL = "https://cozy-worker.jeremycai.workers.dev"