#!/bin/bash

echo "🚀 Cozy Cloud - Quick Test Guide"
echo "================================"
echo ""
echo "1️⃣  First, set up your environment:"
echo "   cp .env.example .env"
echo "   # Edit .env and add your ANTHROPIC_API_KEY"
echo ""
echo "2️⃣  Install dependencies:"
echo "   bun install"
echo ""
echo "3️⃣  Build the container (requires Docker):"
echo "   cd sandbox-image"
echo "   ./build.sh"
echo "   cd .."
echo ""
echo "4️⃣  Start the development server:"
echo "   bun dev"
echo ""
echo "5️⃣  Test Claude Code integration:"
echo "   # In another terminal:"
echo "   bun run test-claude-integration.ts"
echo ""
echo "Or run everything at once with:"
echo "   ./test-quick-start.sh"