#!/bin/bash
echo "🚀 Quick Container Deployment Guide"
echo "=================================="
echo ""
echo "Since Docker isn't available locally, here are your options:"
echo ""
echo "1. Use GitHub Codespaces (Recommended):"
echo "   - Go to https://github.com/your-repo"
echo "   - Click 'Code' → 'Codespaces' → 'Create codespace'"
echo "   - Run these commands:"
echo ""
echo "   cd sandbox-image"
echo "   export CLOUDFLARE_API_TOKEN='SrXIuzVq-PF8G3jeDXTZ9WH26NMJRIQZCysvP5CE'"
echo "   wrangler containers build ."
echo "   wrangler containers push cozy-sandbox:latest"
echo "   cd ../apps/worker"
echo "   wrangler deploy"
echo ""
echo "2. Use Google Cloud Shell (Free):"
echo "   - Go to https://console.cloud.google.com"
echo "   - Click the terminal icon (>_) in the top right"
echo "   - Run the same commands as above"
echo ""
echo "3. Push to GitHub (Automated):"
echo "   - Add secrets to your repo settings:"
echo "     CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID"
echo "   - Push your code:"
echo "     git push origin main"
echo ""
echo "Current Status:"
echo "✅ Worker deployed: https://cozy-backend.botnet-599.workers.dev"
echo "✅ Frontend deployed: https://cozy-frontend.botnet-599.workers.dev"
echo "⏳ Container: Ready to build and deploy"
echo ""
echo "The container includes:"
echo "- Claude Code CLI and SDK"
echo "- Node.js 22 + Python 3.12"
echo "- Isolated execution environment"