name: Build and Push Container to Cloudflare Registry

on:
  push:
    branches:
      - main
    paths:
      - 'sandbox-image/**'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'sandbox-image/**'
      - '.github/workflows/build-container.yml'
  workflow_dispatch:

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Wrangler
      run: npm install -g wrangler
    
    - name: Build Docker image locally
      working-directory: ./sandbox-image
      run: |
        docker build -t cozy-sandbox:latest .
        docker tag cozy-sandbox:latest cozy-sandbox:${{ github.sha }}
    
    - name: Push to Cloudflare Registry
      working-directory: ./sandbox-image
      run: |
        # Push the image using wrangler
        wrangler containers push cozy-sandbox:latest
        wrangler containers push cozy-sandbox:${{ github.sha }}
    
    - name: List images in registry
      run: |
        wrangler containers list