name: Deploy Container (Proper)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install wrangler
      run: |
        npm install -g wrangler@latest
    
    - name: Check Docker
      run: |
        docker --version
        docker info
    
    - name: Deploy Worker with Container
      working-directory: ./apps/worker
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        echo "Deploying worker with container..."
        # This will build, push, and deploy in one command
        wrangler deploy -c wrangler-proper.toml
    
    - name: Check deployment status
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        echo "Checking container status..."
        wrangler containers list
        echo "Checking images..."
        wrangler containers images list