name: Test Build Only

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check secrets
      run: |
        echo "Checking if secrets are available..."
        if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
          echo "ERROR: CLOUDFLARE_API_TOKEN secret is not set!"
        else
          echo "✓ CLOUDFLARE_API_TOKEN is set"
        fi
        if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
          echo "ERROR: CLOUDFLARE_ACCOUNT_ID secret is not set!"
        else
          echo "✓ CLOUDFLARE_ACCOUNT_ID is set"
        fi
    
    - name: Build container
      working-directory: ./sandbox-image
      run: |
        docker build -t cozy-sandbox:latest .
        docker images | grep cozy-sandbox
        echo "✓ Container built successfully!"
    
    - name: Test wrangler
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        npm install -g wrangler
        echo "Testing wrangler authentication..."
        wrangler whoami || echo "Wrangler auth failed"